# Chapter 3 Functions and Packages

## 1) Functions 

- piece of reusable code, aimed at solving a particular task
- call function instead of writing code yourself
- 내장함수(built-in function): 파이썬 표준모듈에 내장되어 있어 import 구문없이 사용가능

In [ ]:
#max(): 최댓값 구하는 파이썬 내장함수
fam=[1.73, 1.68, 1.71, 1.89]
max(fam)  
tallest=max(fam)  #변수에 할당
tallest

1.89

#### round(number[, ndigits]): 반올림하는 내장함수

-input(argument(인자)):

1) number: a number you want to round

2) ndigits: precision with wich to round (소수점 몇 자리까지) (optional argument)

help(round)

In [ ]:
#round(number, ndigits)
round(1.68,1)  

1.7

In [ ]:
#round(number): ndigits가 명시되지 않은 경우, 가장 가까운 정수로 반올림
round(1.68)

2

#### Find Functions (내장함수 찾기)
- standard tasks: probably functions exists
- internet search

In [ ]:
#Familiar Functions 
# Create variables var1 and var2
var1 = [1, 2, 3, 4]
var2 = True

# type(): Print out type of var1
print(type(var1))

# len(): Print out length of var1 (입력값의 요소의 전체 개수 리턴)
print(len(var1))

# int(): Convert var2(boolean) to an integer: out2
out2 = int(var2)  #파이썬에서 True==1, False==0
print(out2)
print(int(False))  

<class 'list'>
4
1
0


In [ ]:
#help(): ask for information about a function
help(complex)
?complex

Help on class complex in module builtins:

class complex(object)
 |  complex(real=0, imag=0)
 |  
 |  Create a complex number from a real part and an optional imaginary part.
 |  
 |  This is equivalent to (real + imag*1j) where imag defaults to 0.
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __divmod__(self, value, /)
 |      Return divmod(self, value).
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __float__(self, /)
 |      float(self)
 |  
 |  __floordiv__(self, value, /)
 |      Return self//value.
 |  
 |  __format__(...)
 |      complex.__format__() -> str
 |      
 |      Convert to a string according to format_spec.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getnewargs__(...)
 |  
 |  __gt__(self, value, /)
 | 

#### Multiple arguments
##### Sorted() 함수
sorted(iterable, /, *, key=None, reverse=False)
- iterable 자료형을 오름차순 정렬(default)하여 리스트로 리턴하는 함수
- iterable: any collection of objects(ex.lists)
- key=None(기본값): 정렬을 목적으로 하는 함수(ex.len, lambda)를 값으로 넣으면, key값을 기준으로 정렬됨 (optional)
- reverse=False(기본값): reverse=True로 설정하면 내림차순 정렬

In [ ]:
help(sorted)

Help on built-in function sorted in module builtins:

sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.
    
    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.



In [ ]:
# sorted()함수 활용하여 내림차순 정렬하기
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]
full=first+second
print(full)

full_sorted=sorted(full,reverse=True)
print(full_sorted)

[11.25, 18.0, 20.0, 10.75, 9.5]
[20.0, 18.0, 11.25, 10.75, 9.5]


## 2) Methods
 -python object: string, float, list etc.(everything=object)
 
 -Methods: functions that belong to objects / call functions on the objects
  - type: str -> methods: capitalize(), replace()
  - type: float -> methods: bit_length(), conjugate()
  - type: list -> methods: index(), count()
  - Python objects have specific methods associated with them, depending on the type

### list methods

In [ ]:
# index(): get the index of the first element of a list that maches the input
fam=['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]
print(fam.index("mom")) 

areas = [11.25, 18.0, 20.0, 10.75, 9.50]
print(areas.index(20.0))

2


In [ ]:
# count(): input 원소가 list에 나타난 횟수 세기
print(fam.count(1.73))

print(areas.count(9.50))

1
1


-Some methods can change the objects they are called on.

ex) append(): 리스트의 요소 추가 (데이터 구조 업데이트 가능)

In [ ]:
# append()
fam=['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]
fam.append("me")
fam.append("1.79")
print(fam)

# Use append twice to add poolhouse and garage size
areas = [11.25, 18.0, 20.0, 10.75, 9.50]
areas.append(24.5)
areas.append(15.45)
print(areas)

['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89, 'me', '1.79']
[11.25, 18.0, 20.0, 10.75, 9.5, 24.5, 15.45]


In [ ]:
# reverse(): Reverse the orders of the elements in the list it is called on
areas.reverse()
print(areas)

[15.45, 24.5, 9.5, 10.75, 20.0, 18.0, 11.25]


In [ ]:
# remove(): removes the first element of a list that matches the input
areas.remove(9.50)
print(areas)

[15.45, 24.5, 10.75, 20.0, 18.0, 11.25]


### string methods

In [ ]:
# capitalize(): 문자열의 첫 글자를 대문자로 바꿈
sister='liz'
sister.capitalize()

In [ ]:
# replace()
sister='liz'
sister.replace("z","sa") #'z'를 'sa'로 대체

'lisa'

In [ ]:
# upper(): 문자열을 대문자로 변환
place = "poolhouse"
place_up=place.upper()
print(place)
print(place_up)

# count(): Print out the number of o's in place
print(place.count("o"))

poolhouse
POOLHOUSE
3


-Objects of different types can have methods with same name 

ex) index() : available for both strings and lists

-object의 type에 따라서 methods가 다르게 작동함

In [ ]:
#index of the letter in the string
sister.index("z") 

2

In [ ]:
#index of the element in the list
fam.index("mom")

## 3) Packages
- Packages: directory of python scripts (모듈을 모아놓은 디렉토리)
- module: each script (함수, 변수, 클래스를 모아놓은 파일)
- specify functions, methods and new python types (aimed at solving particular problems)
- packages for data science
  - numpy: works with array(배열)
  - matplotlib: 데이터 시각화
  - scikit-learn: 머신러닝 
- 패키지 설치 필요 
  - pip 활용: package maintenance system
  - ex) numpy 패키지 설치: pip3 install numpy
- Import package (패키지 불러오기): 크게 두 가지 방법

In [ ]:
#import package
import numpy as np
np.array([1, 2, 3])

array([1, 2, 3])

In [ ]:
#패키지에서 특정 함수만 사용할 경우
from numpy import arrary
array([1, 2, 3])

- 'from ... import' 형식은 코드가 길어질 경우, 어떤 패키지의 함수인지 분명하게 나타나지 않음
- 이러한 점 때문에 'import numpy as np' 형식을 더 선호함 (함수 호출할 때 numpy 패키지 함수인 것을 분명히 알 수 있음)

In [ ]:
# math 패키지 활용하여 원의 넓이/둘레 구하기
r = 0.43 #반지름
import math

#원의 둘레
C = 2*math.pi*r

#원의 넓이
A = math.pi*r**2

print("Circumference: " + str(C))
print("Area: " + str(A))

Circumference: 2.701769682087222
Area: 0.5808804816487527


In [ ]:
# selective import
# Import radians function of math package 
from math import radians

# Travel distance of Moon over 12 degrees.
r = 192500
dist=r*radians(12)
print(dist)

In [ ]:
# Different ways of importing
# ex) scipy.linalg 패키지에서 inv()함수 불러오기
from scipy.linalg import inv as my_inv
my_inv([[1, 2], [3, 4]])

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

-scipy: 과학기술 계산을 위한 파이썬 패키지
 - linalg: 선형대수 계산을 위한 부패키지 (numpy 패키지에도 존재)
  - inv(): 역행렬 구하는 함수