### Logic, Control Flow and Filtering
#### Comparison Operators

- how Python values relate
- makes result boolean
---
- Numeric comparisons

In [18]:
100 < 105

True

In [19]:
2020 == 2021

False

In [20]:
2020 <= 2021

True

In [21]:
x = 2020
y = 2021

x < y

True

- Other comparisons

In [30]:
print('nick' < 'neck')
print('Nick' < 'nick')

False
True


In [31]:
print(ord('i'), ord('e'))
print(ord('N'), ord('n'))

105 101
78 110


- Converts to ASCII numbers and compares characters first
    - ord(): Given a string representing a single Unicode character, returns an integer representing the Unicode code point for that character.
- Typically, Python can't tell how two objects with different type relate
    - without int - float

In [32]:
True < False

False

In [33]:
print(True == 1, False == 0)

True True


- For boolean values, True has a value of 1, False has a value of 0.

- Comparators

|Comparator|Meaning|
|----------|-------|
|<|Strictly less than|
|<=|Less than or equal|
|>|Strictly greater than|
|>=|Greater than or equal|
|==|Equal|
|!=|Not equal|

In [25]:
1 == 1.0

True

In [26]:
1 is 1.0

<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<ipython-input-26-2ebf4c947f31>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
  1 is 1.0


False

In [27]:
id(1)

4309519008

In [28]:
id(1.0)

140270513020560

- is vs. ==
    - is: Verify the id number of the object
        - 1 and 1.0 are different types, but in the sense that they mean the same number, The result is True when compared through the operation ==.
        - 1 and 1.0 mean the same number, but because they are different types and different objects, the result is False when compared through the is operation.

#### Boolean Operators
- and
    - True and True: True
    - True and False: False
    - False and True: False
    - False and False: False
- or
    - True and True: True
    - True and False: True
    - False and True: True
    - False and False: False
- not
    - not True: False
    - not False: True
      
- array
    - The truth value of an array with more than one element is ambiguous
        - logical_and()
        - logical_or()
        - logical_not()

In [35]:
grade = np.array([4.3, 4.1, 3.7, 3.4, 3.2, 4.5])

In [36]:
grade > 3.5

array([ True,  True,  True, False, False,  True])

In [37]:
grade < 4.0

array([False, False,  True,  True,  True, False])

In [38]:
grade > 3.5 and grade < 4.0

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [41]:
np.logical_and(grade > 3.5, grade < 4.0)

array([False, False,  True, False, False, False])

In [42]:
grade[np.logical_and(grade > 3.5, grade < 4.0)]

array([3.7])

#### If, elif, else
- if: if condition, excute expression

In [44]:
grade = 4.5
perfect_grade = 4.5

if grade == perfect_grade:
    print('You got a perfect grade! Congrats!')

You got a perfect grade! Congrats!


- else: Other condition that not condition of if

In [48]:
grade = 3.7
perfect_grade = 4.5

if grade == perfect_grade:
    print('You got a perfect grade! Congrats!')
    
else:
    print('You have to study hard. Keep studying!')

You have to study hard. Keep studying!


In [51]:
grade = 4.3
perfect_grade = 4.5

if grade == perfect_grade:
    print('You got a perfect grade! Congrats!')

elif grade > 4.0:
    print('Excellent. You got a good grade.')

else:
    print('You have to study hard. Keep studying!')

Excellent. You got a good grade.


#### Filtering pandas DataFrames
- Select the area column
    - not Pandas DataFrame, but Pandas Series
    - [], .loc[], .iloc[]
- Do comparison on area column -- step2
    - <, >, <=, >=, ==, !=
    - set variables the result -- result
- Use result to select
    - DataFrame[result]
- DataFrame[DataFrame[step2]]
---
- Using Boolean operators
    - Pandas is based on Numpy, so it can be used
        - np.logical_and, np.logcial_or, np.logical_not