# While Loop

* While : 조건이 True인 경우 내부 코드를 실행 & 조건이 True인 경우, 계속 돌아감.
* 모델과 데이터 사이의 오류가 특정 경계를 벗어날 때까지 반복시켜야 하는 등 반복 작업에 유용


In [2]:
error = 50
while error > 1:
    error = error/4
    print(error)

12.5
3.125
0.78125


# For Loop

In [3]:
fam = [1.73, 1.68, 1.83, 1.86]

In [4]:
print(fam[0])
print(fam[1])
print(fam[2])
print(fam[3])

1.73
1.68
1.83
1.86


In [9]:
# Index를 이용하지 않아도 된다
for h in fam:
    print(h)

1.73
1.68
1.83
1.86


In [11]:
# Index까지 같이 기입하고 싶을 때 : enumerate() - 열거하다
# 각 iteration에서 두 개의 value를 생성
for index, height in enumerate(fam):
    print('index'+str(index)+': '+str(height))

index0: 1.73
index1: 1.68
index2: 1.83
index3: 1.86


* 리스트가 아닌 다른 타입의 변수에도 적용 가능

In [12]:
for c in 'family':
    print(c.capitalize())

F
A
M
I
L
Y


In [13]:
# house list of lists
house = [["hallway", 11.25], 
         ["kitchen", 18.0], 
         ["living room", 20.0], 
         ["bedroom", 10.75], 
         ["bathroom", 9.50]]

for x in house:
    print('the '+x[0]+' is '+str(x[1])+' sqm')

the hallway is 11.25 sqm
the kitchen is 18.0 sqm
the living room is 20.0 sqm
the bedroom is 10.75 sqm
the bathroom is 9.5 sqm


# Loop Data Structure 1

In [15]:
world = {'afghanistan':30.55,
        'albania':2.77,
        'algeria':39.21}

* [key와 value를 추출하고 싶을 때]

* for key, value in world:
* ....print(key+'--'+str(value))
* FAIL

In [17]:
for k,v in world.items():
    print(k+'--'+str(v))

afghanistan--30.55
albania--2.77
algeria--39.21


In [21]:
import numpy as np
np_height = np.array([1.73,1.68,1.71,1.89,1.79])
np_weight = np.array([65.4,59.2,63,6,88.4,68.7])
meas = np.array([np_height,np_weight])

[1.73 1.68 1.71 1.89 1.79]
[65.4 59.2 63.   6.  88.4 68.7]


C:\anaconda\lib\site-packages\ipykernel_launcher.py:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  after removing the cwd from sys.path.


In [24]:
# 반복마다 전체 배열을 인쇄
for v in meas:
    print(v)

[1.73 1.68 1.71 1.89 1.79]
[65.4 59.2 63.   6.  88.4 68.7]


In [32]:
# 배열의 모든 요소를 얻으려면
for v in np.nditer(meas):
    print(v)
# 1.73, 1.68, 1.71, ~~

TypeError: Iterator operand or requested dtype holds references, but the REFS_OK flag was not enabled

# Loop Data Structure 2

In [36]:
dict = {
    'country':['Brazil','Russia','India','China','South Africa'],
    'capital':['Brasilia','Moscow','New Delhi','Beijing','Pretoria'],
    'area':[8.516,17.1,3.286,9.597,1.221],
    'population':[200.4,143.5,1252,1357,52.98]}
import pandas as pd
brics = pd.DataFrame(dict)
brics.index = ['BR','RU','IN','CH','SA']
brics

area    capital       country  population
BR   8.516   Brasilia        Brazil      200.40
RU  17.100     Moscow        Russia      143.50
IN   3.286  New Delhi         India     1252.00
CH   9.597    Beijing         China     1357.00
SA   1.221   Pretoria  South Africa       52.98

In [38]:
for v in brics:
    print(v)
# column name이 나옴.

area
capital
country
population


In [40]:
# iterrows()를 사용하면 행마다 label과 Pandas Series를 출력
for lab,row in brics.iterrows():
    print(lab)
    print(row)

BR
area             8.516
capital       Brasilia
country         Brazil
population       200.4
Name: BR, dtype: object
RU
area            17.1
capital       Moscow
country       Russia
population     143.5
Name: RU, dtype: object
IN
area              3.286
capital       New Delhi
country           India
population         1252
Name: IN, dtype: object
CH
area            9.597
capital       Beijing
country         China
population       1357
Name: CH, dtype: object
SA
area                 1.221
capital           Pretoria
country       South Africa
population           52.98
Name: SA, dtype: object


In [41]:
# capital만 출력하기
for lab,row in brics.iterrows():
    print(lab+': '+row['capital'])

BR: Brasilia
RU: Moscow
IN: New Delhi
CH: Beijing
SA: Pretoria


### Add column

In [45]:
# loc은 label-based
for lab,row in brics.iterrows():
    brics.loc[lab, 'name_length'] = len(row['country'])
brics

area    capital       country  population  name_length
BR   8.516   Brasilia        Brazil      200.40          6.0
RU  17.100     Moscow        Russia      143.50          6.0
IN   3.286  New Delhi         India     1252.00          5.0
CH   9.597    Beijing         China     1357.00          5.0
SA   1.221   Pretoria  South Africa       52.98         12.0

In [49]:
dict = {
    'country':['Brazil','Russia','India','China','South Africa'],
    'capital':['Brasilia','Moscow','New Delhi','Beijing','Pretoria'],
    'area':[8.516,17.1,3.286,9.597,1.221],
    'population':[200.4,143.5,1252,1357,52.98]}
import pandas as pd
brics = pd.DataFrame(dict)
brics.index = ['BR','RU','IN','CH','SA']
print(brics)

# for loop없이 전체 column을 계산하고 싶을 때 : Apply()
# apply()는 len 함수를 각 나라 이름마다 적용
brics['name_length'] = brics['country'].apply(len)
print(brics)

      area    capital       country  population
BR   8.516   Brasilia        Brazil      200.40
RU  17.100     Moscow        Russia      143.50
IN   3.286  New Delhi         India     1252.00
CH   9.597    Beijing         China     1357.00
SA   1.221   Pretoria  South Africa       52.98
      area    capital       country  population  name_length
BR   8.516   Brasilia        Brazil      200.40            6
RU  17.100     Moscow        Russia      143.50            6
IN   3.286  New Delhi         India     1252.00            5
CH   9.597    Beijing         China     1357.00            5
SA   1.221   Pretoria  South Africa       52.98           12


## Quiz

60점을 넘어야 합격인 시험의 결과를 출력하기

In [34]:
marks = [90,25,67,45,80]
n = 0
for m in marks:
    n = n+1
    if m > 60:
        print('%d번 학생은 합격입니다.' %n)
    else:
        print('%d번 학생은 불합격입니다.' %n)

1번 학생은 합격입니다.
2번 학생은 불합격입니다.
3번 학생은 합격입니다.
4번 학생은 불합격입니다.
5번 학생은 합격입니다.


딕셔너리에서 '(국가)의 수도는 (수도)입니다' 출력하기

In [35]:
europe = {'spain':'madrid', 'france':'paris', 'germany':'berlin',
          'norway':'oslo', 'italy':'rome', 'poland':'warsaw', 'austria':'vienna' }

for k,v in europe.items():
    print('the capital of '+k+' is '+v)
    


the capital of spain is madrid
the capital of france is paris
the capital of germany is berlin
the capital of norway is oslo
the capital of italy is rome
the capital of poland is warsaw
the capital of austria is vienna


나라이름을 대문자로 바꾼 열 추가하기

In [52]:
dict = {
    'country':['Brazil','Russia','India','China','South Africa'],
    'capital':['Brasilia','Moscow','New Delhi','Beijing','Pretoria'],
    'area':[8.516,17.1,3.286,9.597,1.221],
    'population':[200.4,143.5,1252,1357,52.98]}

brics = pd.DataFrame(dict)
brics.index = ['BR','RU','IN','CH','SA']

In [55]:
brics['COUNTRY'] = brics['country'].apply(str.upper)
brics

area    capital       country  population       COUNTRY
BR   8.516   Brasilia        Brazil      200.40        BRAZIL
RU  17.100     Moscow        Russia      143.50        RUSSIA
IN   3.286  New Delhi         India     1252.00         INDIA
CH   9.597    Beijing         China     1357.00         CHINA
SA   1.221   Pretoria  South Africa       52.98  SOUTH AFRICA