# 4. NumPy

### NumPy is a fundamental Python package to efficiently practice data science. 

### 수학, 과학 연산을 위한 파이썬의 필수적이고 기본적인 패키지


## 1) NumPy array

#### numpy 배열 생성의 대표적인 방법
#### np.array() 함수 안에 list를 넣어 배열을 생성한다.

In [ ]:
# example.array

baseball = [180, 215, 210, 210, 188, 176, 209, 200]   # baseball 이라는 list 생성
import numpy as np                                   # numpy를 호출해 np로 지정 
np_baseball=np.array(baseball)                        # np.array 함수를 사용해 배열 생성 
print(np_baseball)

[180 215 210 210 188 176 209 200]


In [ ]:
# example.2Darray
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]
import numpy as np
np_baseball=np.array(baseball)
print(np_baseball.shape)         #shape: 배열의 속성 보여줌
print(np_baseball.ndim)          #ndim: 차원을 보여줌
print(np_baseball.size)          #size: 원소의 총 개수를 보여줌
print(np_baseball) 

(4, 2)
2
8
[[180.   78.4]
 [215.  102.7]
 [210.   98.5]
 [188.   75.2]]


## 2) NumPy에서의 연산

#### numpy를 사용하는 이유
#### list 형태에서는 파이썬이 일반적인 계산을 실행할 방법을 모르기 때문에 error가 뜸 (예제 스킵)
#### 반면 numpy를 사용할 경우 리스트 안의 각 원소에 대한 연산으로 인식

In [ ]:
# example.arithmetic
import numpy as np
np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])
mat=([[1, 2],
      [3, 4],
      [5, 6]])
print(mat*2)
print(np_mat * 2)
print(np_mat + np.array([10, 10]))
print(np_mat + np_mat)

[[1, 2], [3, 4], [5, 6], [1, 2], [3, 4], [5, 6]]
[[ 2  4]
 [ 6  8]
 [10 12]]
[[11 12]
 [13 14]
 [15 16]]
[[ 2  4]
 [ 6  8]
 [10 12]]


## 3) Boolean NumPy array
#### 배열 각 요소의 선택여부를 True, False로 표현하는 방식  
#### 특정 요소만을 추출하고 싶을 때 사용 가능

In [ ]:
# example.boolean
import numpy as np
lst = [                        # 3X3의 list 생성:1st
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
a = np.array(lst)
bool_indexing = (a % 2 == 0)   # 배열 a 에 대해 짝수면 True, 홀수면 False (%: 나머지 계산)
print(bool_indexing)
print(a[bool_indexing])        # boolean 인덱스를 사용하여 True인 요소만 뽑아냄

n = a[ a % 2 == 0 ]            # 더 간단한 표현
print(n)

[[False  True False]
 [ True False  True]
 [False  True False]]
[2 4 6 8]
[2 4 6 8]


## 4) NumPy 슬라이싱
#### numpy 배열은 파이썬 리스트와 마찬가지로 슬라이스(Slice)를 지원
#### 각 차원별로 슬라이스 범위를 지정

In [ ]:
# example.slice
import numpy as np
lst = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
arr = np.array(lst)
a = arr[0:2, 0:2]   # 행(0,1)과 열(0,1)를 호출
print(a)
a = arr[1:, 1:]     # 행(2,3)과 열(2,3)을 호출
print(a)

[[1 2]
 [4 5]]
[[5 6]
 [8 9]]


## 5) NumPy 함수들
#### https://codetorial.net/numpy/functions/index.html 다양한 함수들이 있음 (예제 스킵)

# 번외: 머신러닝에서의 numpy

### 분석자료를 생성하고 편집, 가공, 연산하는 라이브러리

## 1) 텐서의 형성

#### 텐서: 머신러닝/딥러닝에서 사용하는 자료의 차원을 말함  ex) 1D tensor: vector, 2D tensor: matrix, 3d tensor: image...
#### ㄱ) zeros/ones 등의 함수를 사용해 '모수의 초기치'를 만드는데 유용하게 사용
#### ㄴ) linspace/arange 등의 함수는 범위를 지정해 생성 *linspace는 그래프의 x축, y축을 표현할 때 유용하게 사용

In [ ]:
# exercise.init

print(np.zeros(5,dtype=int))
print(np.ones([2,3],dtype=float))

[0 0 0 0 0]
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# exercise.ran

print(np.arange(0,10,2))
print(np.linspace(0,1,5))

[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


## 2) 특정 분포의 확률변수 값 생성

In [ ]:
# seed
np.random.seed(12)                          # 랜덤으로 지정된 확률변수 값을 동일하게 생성할 수 있도록 사용
 
# uniform
print(np.random.random((3,3)))              # Uniform(0,1)에서 3X3의 행렬 생성

#normal
print(np.random.normal(0,1,(3,3)))          # 평균이 0이고 분산이 1인 정규분포로부터 3X3의 행렬 생성
print(np.random.normal(0,1,size=(2,3,4)))   # 3차원일 경우 size 사용

#others
np.random?;np.random??

[[0.15416284 0.7400497  0.26331502]
 [0.53373939 0.01457496 0.91874701]
 [0.90071485 0.03342143 0.95694934]]
[[-0.42069204 -0.7060276   0.58535808]
 [ 0.13978644  2.73781428  1.11674795]
 [ 1.57453814 -0.08586679  0.47673663]]
[[[-0.61138674 -0.34947094 -0.70541676 -0.34018626]
  [ 2.02729871 -0.58108011  0.87313484  0.91056528]
  [ 1.04764561 -1.18963857 -1.24056205  0.05530221]]

 [[ 0.21221081 -0.34532435  1.20216335 -2.20559351]
  [-1.08076492 -0.08614659  0.49351428 -1.16446595]
  [-2.39988134 -0.61006418 -2.23348044  0.79475247]]]


In [ ]:
np.random.random((3,3))

array([[0.0208098 , 0.13521018, 0.11627302],
       [0.30989758, 0.67145265, 0.47122978],
       [0.8161683 , 0.28958678, 0.73312598]])

In [ ]:
np.random.seed(12)
np.random.random((3,3))

array([[0.15416284, 0.7400497 , 0.26331502],
       [0.53373939, 0.01457496, 0.91874701],
       [0.90071485, 0.03342143, 0.95694934]])

## 3) NumPy 분할/덧붙이기
#### ㄱ) 분할: 한 개의 자료를 두 개 이상으로 나누는 과정
#### - 머신러닝에서, 자료를 학습데이터(training data)와 시험데이터(test data)로 나누어 모형을 학습데이터에 적합시키고 이 적합된 모형을    시험데이터에 적용 (실제로는 sklearn model_selection의 train_test_split을 많이 사용)
#### ex) np.split(), np.vsplit(), np.hsplit()
#### ㄴ) 덧붙이기: 두 개 이상의 자료를 하나의 자료로 합치는 과정
#### - 자료의 분석을 위해 자료를 합쳐야 하는 경우 발생
#### ex) np.concatenate(), np.hstack(), np.vstack()

In [ ]:
# exercise.분할

x=[1,2,3,4,5,6,7,8]
x1,x2,x3=np.split(x,[2,6])   # index를 [0,2), [2,6), [6,마지막 index]로 분류
print(x1,x2,x3)

x=np.random.random((4,4))   
x1,x2=np.vsplit(x,[2])      #배열을 행 방향으로 분류
print(x)
print(x1)
print(x2)

[1 2] [3 4 5 6] [7 8]
[[0.34755146 0.61310231 0.00968651 0.9242855 ]
 [0.85772862 0.86437331 0.71009535 0.11277398]
 [0.46346445 0.05103969 0.95271268 0.26500428]
 [0.56690714 0.02856208 0.7344704  0.76767865]]
[[0.34755146 0.61310231 0.00968651 0.9242855 ]
 [0.85772862 0.86437331 0.71009535 0.11277398]]
[[0.46346445 0.05103969 0.95271268 0.26500428]
 [0.56690714 0.02856208 0.7344704  0.76767865]]


In [ ]:
# exercise.덧붙이기

x=np.array([1,2])
y=np.array([2,3])
z=np.array([4,5])
xyz=np.concatenate([x,y,z])
print(xyz)

xx=np.array([[1,2,3],[4,5,6]])
yy=np.array([[2,4,6],[8,7,6]])
xxyy=np.concatenate([xx,yy])          # np.vstack()
print(xxyy)

xxyy=np.concatenate([xx,yy],axis=1)   # np.hstack()
print(xxyy)

[1 2 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [2 4 6]
 [8 7 6]]
[[1 2 3 2 4 6]
 [4 5 6 8 7 6]]


## 4) 기타

#### 1. np.where(A,a,b): 조건 A를 만족하면 값 a를 부여하고 만족하지 못하면 값 b를 부여 (if and else 문)
#### 2. np.unique(): 중복되는 값을 하나로 정리
#### 3. np.exp(), np.log() / np.cov(), np.mean(), np.std() 등의 확률분포, 특정 함수 값이나 통계량 계산